baseURL = "https://vitess.io"
canonifyurls = true
disableKinds = ["taxonomy", "taxonomyTerm"]

# Syntax highlighting settings
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "fruity"

[params.home]
title = "Vitess is a database clustering system for horizontal scaling of MySQL"

[params.assets]
js = ["jquery-3.3.1", "jquery-ui-1.12.1", "jquery.tocify-1.9.0", "app"]
fontawesomeversion = "5.7.2"

[params.social]
github        = "vitessio/vitess"
twitter       = "vitessio"
slack         = "https://vitess.slack.com/join/shared_invite/enQtMzIxMDMyMzA0NzA1LTBjYjY1M2I2Yjg5YmY3ODIwOTk0N2M1YzI4Y2ViODdiNmIxMDdiMDM5YWQ1ZTc0YmJhZDdiOTliMGVkNDY4MjM"
stackoverflow = "vitess"

[params.blog]
subtitle = "Updates and insights from the **Vitess** team."

# Language settings
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
contentDir = "content/en"

[languages]
[languages.en]
title   = "Vitess"
description = "A database clustering system for horizontal scaling of MySQL"
languageName = "English"
weight = 1

[languages.zh]
title = "Vitess"
description = "A database clustering system for horizontal scaling of MySQL"
languageName = "中文 Chinese"
weight = 2

